version: 2

jobs:
  test:
    working_directory: ~/materialize-react
    docker:
      - image: circleci/node:4
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Lint
          command: yarn run lint
      - run:
          name: Run Tests & Check Coverage
          command: yarn run test:coverage
      - run:
          name: Report Coverage
          command: yarn run report-coverage

  deploy_storybook:
    working_directory: ~/materialize-react
    docker:
      - image: circleci/node:4
    branches:
      only:
        - master
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Deploy Storybook
          command: yarn run deploy-storybook

workflows:
  version: 2

  test_and_deploy:
    jobs:
      - test
      - deploy_storybook:
          requires:
            - test
          filters:
            branches:
              only: master
