version: 2

jobs:
  lint:
    working_directory: ~/materialize-react
    docker:
      - image: circleci/node:6@sha256:575a3e2e090b30f69ed14b1137e49d6cb4cfbbab69c182de40349b690bf8a7e3
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Lint
          command: yarn run lint

  flow:
    working_directory: ~/materialize-react
    docker:
      - image: circleci/node:6@sha256:575a3e2e090b30f69ed14b1137e49d6cb4cfbbab69c182de40349b690bf8a7e3
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Lint
          command: yarn run flow

  test:
    working_directory: ~/materialize-react
    docker:
      - image: circleci/node:8@sha256:744c0829877ab7f73473d0553f1df84efc9d50f4cdc1cd256a4b0c271834b40d
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Run Tests & Check Coverage
          command: yarn run test:coverage

  build:
    working_directory: ~/materialize-react
    docker:
      - image: circleci/node:8@sha256:744c0829877ab7f73473d0553f1df84efc9d50f4cdc1cd256a4b0c271834b40d
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Build
          command: yarn run build

workflows:
  version: 2

  test:
    jobs:
      - lint
      - flow
      - test
      - build
